/*
Navicat MySQL Data Transfer

Source Server         : mysqllocal
Source Server Version : 50721
Source Host           : localhost:3306
Source Database       : my-shop

Target Server Type    : MYSQL
Target Server Version : 50721
File Encoding         : 65001

Date: 2018-06-04 17:43:49
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Records of sys_menu
-- ----------------------------
INSERT INTO `sys_menu` VALUES ('1', '0', '系统管理', null, null, '0', 'fa fa-cog', '11', '0');
INSERT INTO `sys_menu` VALUES ('2', '1', '管理员列表', 'sys/user.html', null, '1', 'fa fa-user', '1', '0');
INSERT INTO `sys_menu` VALUES ('3', '1', '角色管理', 'sys/role.html', null, '1', 'fa fa-user-secret', '2', '0');
INSERT INTO `sys_menu` VALUES ('4', '1', '菜单管理', 'sys/menu.html', null, '1', 'fa fa-folder-open', '4', '0');
INSERT INTO `sys_menu` VALUES ('5', '1', 'SQL监控', 'druid/sql.html', null, '1', 'fa fa-linux', '9', '0');
INSERT INTO `sys_menu` VALUES ('6', '1', '定时任务', 'sys/schedule.html', null, '1', 'fa fa-tasks', '5', '0');
INSERT INTO `sys_menu` VALUES ('7', '6', '查看', null, 'sys:schedule:list,sys:schedule:info', '2', null, '0', '0');
INSERT INTO `sys_menu` VALUES ('8', '6', '新增', null, 'sys:schedule:save', '2', null, '0', '0');
INSERT INTO `sys_menu` VALUES ('9', '6', '修改', null, 'sys:schedule:update', '2', null, '0', '0');
INSERT INTO `sys_menu` VALUES ('10', '6', '删除', null, 'sys:schedule:delete', '2', null, '0', '0');
INSERT INTO `sys_menu` VALUES ('11', '6', '暂停', null, 'sys:schedule:pause', '2', null, '0', '0');
INSERT INTO `sys_menu` VALUES ('12', '6', '恢复', null, 'sys:schedule:resume', '2', null, '0', '0');
INSERT INTO `sys_menu` VALUES ('13', '6', '立即执行', null, 'sys:schedule:run', '2', null, '0', '0');
INSERT INTO `sys_menu` VALUES ('14', '6', '日志列表', null, 'sys:schedule:log', '2', null, '0', '0');
INSERT INTO `sys_menu` VALUES ('15', '2', '查看', null, 'sys:user:list,sys:user:info', '2', null, '0', '0');
INSERT INTO `sys_menu` VALUES ('16', '2', '新增', null, 'sys:user:save,sys:role:select', '2', null, '0', '0');
INSERT INTO `sys_menu` VALUES ('17', '2', '修改', null, 'sys:user:update,sys:role:select', '2', null, '0', '0');
INSERT INTO `sys_menu` VALUES ('18', '2', '删除', null, 'sys:user:delete', '2', null, '0', '0');
INSERT INTO `sys_menu` VALUES ('19', '3', '查看', null, 'sys:role:list,sys:role:info', '2', null, '0', '0');
INSERT INTO `sys_menu` VALUES ('20', '3', '新增', null, 'sys:role:save,sys:menu:perms', '2', null, '0', '0');
INSERT INTO `sys_menu` VALUES ('21', '3', '修改', null, 'sys:role:update,sys:menu:perms', '2', null, '0', '0');
INSERT INTO `sys_menu` VALUES ('22', '3', '删除', null, 'sys:role:delete', '2', null, '0', '0');
INSERT INTO `sys_menu` VALUES ('23', '4', '查看', null, 'sys:menu:list,sys:menu:info', '2', null, '0', '0');
INSERT INTO `sys_menu` VALUES ('24', '4', '新增', null, 'sys:menu:save,sys:menu:select', '2', null, '0', '0');
INSERT INTO `sys_menu` VALUES ('25', '4', '修改', null, 'sys:menu:update,sys:menu:select', '2', null, '0', '0');
INSERT INTO `sys_menu` VALUES ('26', '4', '删除', null, 'sys:menu:delete', '2', null, '0', '0');
INSERT INTO `sys_menu` VALUES ('27', '1', '系统参数', 'sys/config.html', 'sys:config:list,sys:config:info,sys:config:save,sys:config:update,sys:config:delete', '1', 'fa fa-sun-o', '7', '0');
INSERT INTO `sys_menu` VALUES ('28', '1', '代码生成器', 'sys/generator.html', 'sys:generator:list,sys:generator:code', '1', 'fa fa-rocket', '10', '0');
INSERT INTO `sys_menu` VALUES ('29', '1', '系统日志', 'sys/log.html', 'sys:log:list', '1', 'fa fa-file-text-o', '8', '0');
INSERT INTO `sys_menu` VALUES ('30', '1', '文件上传', 'sys/oss.html', 'sys:oss:all', '1', 'fa fa-file-image-o', '6', '0');
INSERT INTO `sys_menu` VALUES ('200', '0', '会员管理', null, null, '0', 'fa fa-user-circle-o', '1', '0');
INSERT INTO `sys_menu` VALUES ('201', '200', '会员管理', 'shop/shopuser.html', null, '1', 'fa fa-user-md', '1', '0');
INSERT INTO `sys_menu` VALUES ('202', '201', '查看', null, 'user:list,user:info', '2', null, '0', '0');
INSERT INTO `sys_menu` VALUES ('203', '201', '新增', null, 'user:save', '2', null, '0', '0');
INSERT INTO `sys_menu` VALUES ('204', '201', '修改', null, 'user:update', '2', null, '0', '0');
INSERT INTO `sys_menu` VALUES ('205', '201', '删除', null, 'user:delete', '2', null, '0', '0');
INSERT INTO `sys_menu` VALUES ('207', '200', '会员等级', 'shop/userlevel.html', null, '1', 'fa fa-star-o', '0', '1');
INSERT INTO `sys_menu` VALUES ('208', '207', '查看', null, 'userlevel:list,userlevel:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('209', '207', '新增', null, 'userlevel:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('210', '207', '修改', null, 'userlevel:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('211', '207', '删除', null, 'userlevel:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('212', '200', '收货地址管理', 'shop/address.html', null, '1', 'fa fa-map-marker', '6', '0');
INSERT INTO `sys_menu` VALUES ('213', '212', '查看', null, 'address:list,address:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('214', '212', '新增', null, 'address:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('215', '212', '修改', null, 'address:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('216', '212', '删除', null, 'address:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('222', '0', '商城管理', null, null, '0', 'fa fa-shopping-cart', '2', '0');
INSERT INTO `sys_menu` VALUES ('223', '222', '商品属性种类', 'shop/attributecategory.html', null, '1', 'fa fa-sun-o', '0', '0');
INSERT INTO `sys_menu` VALUES ('224', '223', '查看', null, 'attributecategory:list,attributecategory:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('225', '223', '新增', null, 'attributecategory:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('226', '223', '修改', null, 'attributecategory:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('227', '223', '删除', null, 'attributecategory:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('233', '243', '广告列表', 'shop/ad.html', null, '1', 'fa fa-pencil', '1', '0');
INSERT INTO `sys_menu` VALUES ('234', '233', '查看', null, 'ad:list,ad:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('235', '233', '新增', null, 'ad:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('236', '233', '修改', null, 'ad:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('237', '233', '删除', null, 'ad:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('238', '243', '广告位置', 'shop/adposition.html', null, '1', 'fa fa-map-pin', '0', '0');
INSERT INTO `sys_menu` VALUES ('239', '238', '查看', null, 'adposition:list,adposition:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('240', '238', '新增', null, 'adposition:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('241', '238', '修改', null, 'adposition:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('242', '238', '删除', null, 'adposition:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('243', '0', '推广管理', null, null, '0', 'fa fa-hand-paper-o', '5', '0');
INSERT INTO `sys_menu` VALUES ('244', '243', '优惠劵管理', 'shop/coupon.html', null, '1', 'fa fa-cc-visa', '2', '0');
INSERT INTO `sys_menu` VALUES ('245', '244', '查看', null, 'coupon:list,coupon:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('246', '244', '新增', null, 'coupon:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('247', '244', '修改', null, 'coupon:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('248', '244', '删除', null, 'coupon:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('249', '200', '会员优惠劵', 'shop/usercoupon.html', null, '1', 'fa fa-cc-visa', '2', '0');
INSERT INTO `sys_menu` VALUES ('250', '249', '查看', null, 'usercoupon:list,usercoupon:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('251', '249', '新增', null, 'usercoupon:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('252', '249', '修改', null, 'usercoupon:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('253', '249', '删除', null, 'usercoupon:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('254', '222', '品牌制造商', 'shop/brand.html', null, '1', 'fa fa-registered', '5', '0');
INSERT INTO `sys_menu` VALUES ('255', '254', '查看', null, 'brand:list,brand:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('256', '254', '新增', null, 'brand:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('257', '254', '修改', null, 'brand:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('258', '254', '删除', null, 'brand:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('259', '222', '商品规格', 'shop/specification.html', null, '1', 'fa fa-hand-rock-o', '1', '0');
INSERT INTO `sys_menu` VALUES ('260', '259', '查看', null, 'specification:list,specification:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('261', '259', '新增', null, 'specification:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('262', '259', '修改', null, 'specification:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('263', '259', '删除', null, 'specification:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('264', '200', '会员收藏', 'shop/collect.html', null, '1', 'fa fa-star', '3', '0');
INSERT INTO `sys_menu` VALUES ('265', '264', '查看', null, 'collect:list,collect:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('266', '264', '删除', null, 'collect:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('270', '243', '专题管理', 'shop/topic.html', null, '1', 'fa fa-ticket', '5', '1');
INSERT INTO `sys_menu` VALUES ('271', '270', '查看', null, 'topic:list,topic:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('272', '270', '新增', null, 'topic:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('273', '270', '修改', null, 'topic:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('274', '270', '删除', null, 'topic:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('275', '243', '专题分类', 'shop/topiccategory.html', null, '1', 'fa fa-tint', '4', '1');
INSERT INTO `sys_menu` VALUES ('276', '275', '查看', null, 'topiccategory:list,topiccategory:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('277', '275', '新增', null, 'topiccategory:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('278', '275', '修改', null, 'topiccategory:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('279', '275', '删除', null, 'topiccategory:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('280', '200', '会员足迹', 'shop/footprint.html', null, '1', 'fa fa-history', '6', '0');
INSERT INTO `sys_menu` VALUES ('281', '280', '查看', null, 'footprint:list,footprint:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('282', '280', '删除', null, 'footprint:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('283', '200', '搜索历史', 'shop/searchhistory.html', null, '1', 'fa fa-search', '6', '0');
INSERT INTO `sys_menu` VALUES ('284', '283', '查看', null, 'searchhistory:list,searchhistory:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('285', '283', '删除', null, 'searchhistory:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('286', '200', '购物车', 'shop/cart.html', null, '1', 'fa fa-shopping-cart', '6', '0');
INSERT INTO `sys_menu` VALUES ('287', '286', '查看', null, 'cart:list,cart:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('288', '286', '删除', null, 'cart:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('289', '357', '商品管理', 'shop/goods.html', null, '1', 'fa fa-shopping-bag', '1', '0');
INSERT INTO `sys_menu` VALUES ('290', '289', '查看', null, 'goods:list,goods:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('291', '289', '新增', null, 'goods:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('292', '289', '修改', null, 'goods:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('293', '289', '删除', null, 'goods:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('294', '374', '订单管理', 'order/order.html', null, '1', 'fa fa-sitemap', '6', '0');
INSERT INTO `sys_menu` VALUES ('295', '294', '查看', null, 'order:list,order:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('296', '294', '发货', null, 'order:sendGoods', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('297', '222', '商品类型', 'shop/category.html', null, '1', 'fa fa-ship', '3', '0');
INSERT INTO `sys_menu` VALUES ('298', '297', '查看', null, 'category:list,category:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('299', '297', '新增', null, 'category:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('300', '297', '修改', null, 'category:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('301', '297', '删除', null, 'category:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('302', '1', '通用字典表', 'sys/macro.html', null, '1', 'fa fa-book', '6', '0');
INSERT INTO `sys_menu` VALUES ('303', '302', '查看', null, 'sys:macro:list,sys:macro:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('304', '302', '新增', null, 'sys:macro:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('305', '302', '修改', null, 'sys:macro:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('306', '302', '删除', null, 'sys:macro:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('307', '222', '渠道管理', 'shop/channel.html', null, '1', 'fa fa-road', '2', '1');
INSERT INTO `sys_menu` VALUES ('308', '307', '查看', null, 'channel:list,channel:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('309', '307', '新增', null, 'channel:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('310', '307', '修改', null, 'channel:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('311', '307', '删除', null, 'channel:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('312', '0', '微信管理', null, null, '0', 'fa fa-weixin', '6', '0');
INSERT INTO `sys_menu` VALUES ('313', '0', '库存管理', null, null, '0', 'fa fa-cog', '6', '0');
INSERT INTO `sys_menu` VALUES ('314', '0', '报表管理', null, null, '0', 'fa fa-line-chart', '7', '0');
INSERT INTO `sys_menu` VALUES ('315', '222', '商品问答', 'shop/goodsissue.html', null, '1', 'fa fa-question-circle-o', '6', '0');
INSERT INTO `sys_menu` VALUES ('316', '315', '查看', null, 'goodsissue:list,goodsissue:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('317', '315', '新增', null, 'goodsissue:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('318', '315', '修改', null, 'goodsissue:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('319', '315', '删除', null, 'goodsissue:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('325', '222', '反馈', 'shop/feedback.html', null, '1', 'fa fa-mail-reply-all', '6', '0');
INSERT INTO `sys_menu` VALUES ('326', '325', '查看', null, 'feedback:list,feedback:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('327', '325', '新增', null, 'feedback:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('328', '325', '修改', null, 'feedback:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('329', '325', '删除', null, 'feedback:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('330', '244', '发放', null, 'coupon:publish', '2', null, '4', '0');
INSERT INTO `sys_menu` VALUES ('331', '222', '关键词', 'shop/keywords.html', null, '1', 'fa fa-underline', '6', '0');
INSERT INTO `sys_menu` VALUES ('332', '331', '查看', null, 'keywords:list,keywords:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('333', '331', '新增', null, 'keywords:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('334', '331', '修改', null, 'keywords:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('335', '331', '删除', null, 'keywords:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('336', '357', '用户评论', 'shop/comment.html', null, '1', 'fa fa-commenting', '6', '0');
INSERT INTO `sys_menu` VALUES ('337', '336', '查看', null, 'comment:list,comment:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('338', '336', '新增', null, 'comment:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('339', '336', '修改', null, 'comment:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('340', '336', '删除', null, 'comment:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('341', '336', '修改状态', null, 'comment:toggleStatus', '2', null, '0', '0');
INSERT INTO `sys_menu` VALUES ('342', '357', '产品设置', 'shop/product.html', null, '1', 'fa fa-paypal', '3', '0');
INSERT INTO `sys_menu` VALUES ('343', '342', '查看', null, 'product:list,product:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('344', '342', '新增', null, 'product:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('345', '342', '修改', null, 'product:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('346', '342', '删除', null, 'product:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('352', '357', '商品规格', 'shop/goodsspecification.html', null, '1', 'fa fa-deafness', '2', '0');
INSERT INTO `sys_menu` VALUES ('353', '352', '查看', null, 'goodsspecification:list,goodsspecification:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('354', '352', '新增', null, 'goodsspecification:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('355', '352', '修改', null, 'goodsspecification:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('356', '352', '删除', null, 'goodsspecification:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('357', '0', '商品管理', null, null, '0', 'fa fa-edit', '3', '0');
INSERT INTO `sys_menu` VALUES ('358', '357', '商品回收站', 'shop/goodshistory.html', '', '1', 'fa fa-history', '12', '0');
INSERT INTO `sys_menu` VALUES ('359', '358', '恢复', null, 'goods:back', '2', null, '0', '0');
INSERT INTO `sys_menu` VALUES ('360', '294', '确认收货', null, 'order:confirm', '2', null, '0', '0');
INSERT INTO `sys_menu` VALUES ('368', '1', '部门管理', 'sys/dept.html', null, '1', 'fa fa-sitemap', '3', '0');
INSERT INTO `sys_menu` VALUES ('369', '368', '查看', null, 'sys:dept:list,sys:dept:info', '2', null, '0', '0');
INSERT INTO `sys_menu` VALUES ('370', '368', '新增', null, 'sys:dept:save', '2', null, '0', '0');
INSERT INTO `sys_menu` VALUES ('371', '368', '修改', null, 'sys:dept:update', '2', null, '0', '0');
INSERT INTO `sys_menu` VALUES ('372', '368', '删除', null, 'sys:dept:delete', '2', null, '0', '0');
INSERT INTO `sys_menu` VALUES ('373', '368', '选择部门', null, 'sys:dept:select', '2', null, '0', '0');
INSERT INTO `sys_menu` VALUES ('374', '0', '订单管理', null, null, '0', 'fa fa-first-order', '4', '0');
INSERT INTO `sys_menu` VALUES ('375', '0', '短信平台', null, null, '0', 'fa fa-television', '9', '0');
INSERT INTO `sys_menu` VALUES ('376', '375', '短信配置', 'sys/smslog.html', 'sys:smslog:list,sys:smslog:info', '1', 'fa fa-envelope-open', '1', '0');
INSERT INTO `sys_menu` VALUES ('377', '1', '地区管理', 'sys/region.html', null, '1', 'fa fa-map-pin', '8', '0');
INSERT INTO `sys_menu` VALUES ('378', '377', '删除', null, 'sys:region:delete', '2', null, '0', '0');
INSERT INTO `sys_menu` VALUES ('379', '377', '修改', '', 'sys:region:update', '2', null, '0', '0');
INSERT INTO `sys_menu` VALUES ('380', '377', '新增', null, 'sys:region:save', '2', null, '0', '0');
INSERT INTO `sys_menu` VALUES ('381', '377', '查看', null, 'sys:region:list,sys:region:info', '2', null, '0', '0');
INSERT INTO `sys_menu` VALUES ('392', '312', '微信会员', 'wx/wxuser.html', null, '1', 'fa fa-file-code-o', '6', '0');
INSERT INTO `sys_menu` VALUES ('393', '392', '查看', null, 'wxuser:list,wxuser:info', '2', '', '6', '0');
INSERT INTO `sys_menu` VALUES ('394', '392', '新增', null, 'wxuser:save', '2', '', '6', '0');
INSERT INTO `sys_menu` VALUES ('395', '392', '修改', null, 'wxuser:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('396', '392', '删除', null, 'wxuser:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('397', '312', '会员列表', 'wx/wxuser.html', null, '1', 'fa fa-file-code-o', '6', '0');
INSERT INTO `sys_menu` VALUES ('398', '397', '查看', null, 'wxuser:list,wxuser:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('399', '397', '新增', null, 'wxuser:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('400', '397', '修改', null, 'wxuser:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('401', '397', '删除', null, 'wxuser:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('402', '312', '微信配置', 'wx/wxconfig.html', null, '1', 'fa fa-file-code-o', '6', '0');
INSERT INTO `sys_menu` VALUES ('403', '402', '查看', null, 'wxconfig:list,wxconfig:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('404', '402', '新增', null, 'wxconfig:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('405', '402', '修改', null, 'wxconfig:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('406', '402', '删除', null, 'wxconfig:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('407', '312', '菜单配置', 'wx/wxmenu.html', null, '1', 'fa fa-file-code-o', '6', '0');
INSERT INTO `sys_menu` VALUES ('408', '407', '查看', null, 'wxmenu:list,wxmenu:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('409', '407', '新增', null, 'wxmenu:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('410', '407', '修改', null, 'wxmenu:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('411', '407', '删除', null, 'wxmenu:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('412', '312', '回复消息', 'wx/wxmsgreply.html', null, '1', 'fa fa-file-code-o', '6', '0');
INSERT INTO `sys_menu` VALUES ('413', '412', '查看', null, 'wxmsgreply:list,wxmsgreply:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('414', '412', '新增', null, 'wxmsgreply:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('415', '412', '修改', null, 'wxmsgreply:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('416', '412', '删除', null, 'wxmsgreply:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('417', '312', '回复内容', 'wx/wxreply.html', null, '1', 'fa fa-file-code-o', '6', '0');
INSERT INTO `sys_menu` VALUES ('418', '417', '查看', null, 'wxreply:list,wxreply:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('419', '417', '新增', null, 'wxreply:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('420', '417', '修改', null, 'wxreply:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('421', '417', '删除', null, 'wxreply:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('422', '312', '回复关键字', 'wx/wxreply.html', null, '1', 'fa fa-file-code-o', '6', '0');
INSERT INTO `sys_menu` VALUES ('423', '422', '查看', null, 'wxreply:list,wxreply:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('424', '422', '新增', null, 'wxreply:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('425', '422', '修改', null, 'wxreply:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('426', '422', '删除', null, 'wxreply:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('427', '312', '群发列表', 'wx/wxmasssend.html', null, '1', 'fa fa-file-code-o', '6', '0');
INSERT INTO `sys_menu` VALUES ('428', '427', '查看', null, 'wxmasssend:list,wxmasssend:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('429', '427', '新增', null, 'wxmasssend:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('430', '427', '修改', null, 'wxmasssend:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('431', '427', '删除', null, 'wxmasssend:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('432', '312', '会员消息', 'wx/wxmsg.html', null, '1', 'fa fa-file-code-o', '6', '0');
INSERT INTO `sys_menu` VALUES ('433', '432', '查看', null, 'wxmsg:list,wxmsg:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('434', '432', '新增', null, 'wxmsg:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('435', '432', '修改', null, 'wxmsg:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('436', '432', '删除', null, 'wxmsg:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('437', '312', '群发消息', 'wx/wxmass.html', null, '1', 'fa fa-file-code-o', '6', '0');
INSERT INTO `sys_menu` VALUES ('438', '437', '查看', null, 'wxmass:list,wxmass:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('439', '437', '新增', null, 'wxmass:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('440', '437', '修改', null, 'wxmass:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('441', '437', '删除', null, 'wxmass:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('442', '312', '文本回复', 'wx/wxreplytxt.html', null, '1', 'fa fa-file-code-o', '6', '0');
INSERT INTO `sys_menu` VALUES ('443', '442', '查看', null, 'wxreplytxt:list,wxreplytxt:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('444', '442', '新增', null, 'wxreplytxt:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('445', '442', '修改', null, 'wxreplytxt:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('446', '442', '删除', null, 'wxreplytxt:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('447', '312', '新增群发消息', 'wx/wxmassnews.html', null, '1', 'fa fa-file-code-o', '6', '0');
INSERT INTO `sys_menu` VALUES ('448', '447', '查看', null, 'wxmassnews:list,wxmassnews:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('449', '447', '新增', null, 'wxmassnews:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('450', '447', '修改', null, 'wxmassnews:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('451', '447', '删除', null, 'wxmassnews:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('452', '312', '图文回复', 'wx/wxreplynews.html', null, '1', 'fa fa-file-code-o', '6', '0');
INSERT INTO `sys_menu` VALUES ('453', '452', '查看', null, 'wxreplynews:list,wxreplynews:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('454', '452', '新增', null, 'wxreplynews:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('455', '452', '修改', null, 'wxreplynews:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('456', '452', '删除', null, 'wxreplynews:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('457', '312', '模板编号', 'wx/wxtplid.html', null, '1', 'fa fa-file-code-o', '6', '0');
INSERT INTO `sys_menu` VALUES ('458', '457', '查看', null, 'wxtplid:list,wxtplid:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('459', '457', '新增', null, 'wxtplid:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('460', '457', '修改', null, 'wxtplid:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('461', '457', '删除', null, 'wxtplid:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('462', '312', '模板列表', 'wx/wxtpllist.html', null, '1', 'fa fa-file-code-o', '6', '0');
INSERT INTO `sys_menu` VALUES ('463', '462', '查看', null, 'wxtpllist:list,wxtpllist:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('464', '462', '新增', null, 'wxtpllist:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('465', '462', '修改', null, 'wxtpllist:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('466', '462', '删除', null, 'wxtpllist:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('467', '312', '模板发送记录', 'wx/wxtpllog.html', null, '1', 'fa fa-file-code-o', '6', '0');
INSERT INTO `sys_menu` VALUES ('468', '467', '查看', null, 'wxtpllog:list,wxtpllog:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('469', '467', '新增', null, 'wxtpllog:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('470', '467', '修改', null, 'wxtpllog:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('471', '467', '删除', null, 'wxtpllog:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('472', '0', 'CMS管理', null, null, '0', 'fa fa-cog', '6', '0');
INSERT INTO `sys_menu` VALUES ('473', '472', '栏目管理', 'cms/cmschannel.html', null, '1', 'fa fa-file-code-o', '6', '0');
INSERT INTO `sys_menu` VALUES ('474', '473', '查看', null, 'cmschannel:list,cmschannel:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('475', '473', '新增', null, 'cmschannel:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('476', '473', '修改', null, 'cmschannel:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('477', '473', '删除', null, 'cmschannel:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('478', '472', '链接分类', 'cms/cmslinkclass.html', null, '1', 'fa fa-file-code-o', '6', '0');
INSERT INTO `sys_menu` VALUES ('479', '478', '查看', null, 'cmslinkclass:list,cmslinkclass:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('480', '478', '新增', null, 'cmslinkclass:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('481', '478', '修改', null, 'cmslinkclass:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('482', '478', '删除', null, 'cmslinkclass:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('483', '472', '文章管理', 'cms/cmsarticle.html', null, '1', 'fa fa-file-code-o', '6', '0');
INSERT INTO `sys_menu` VALUES ('484', '483', '查看', null, 'cmsarticle:list,cmsarticle:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('485', '483', '新增', null, 'cmsarticle:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('486', '483', '修改', null, 'cmsarticle:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('487', '483', '删除', null, 'cmsarticle:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('488', '472', '链接管理', 'cms/cmslink.html', null, '1', 'fa fa-file-code-o', '6', '0');
INSERT INTO `sys_menu` VALUES ('489', '488', '查看', null, 'cmslink:list,cmslink:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('490', '488', '新增', null, 'cmslink:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('491', '488', '修改', null, 'cmslink:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('492', '488', '删除', null, 'cmslink:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('493', '472', '站点管理', 'cms/cmssite.html', null, '1', 'fa fa-file-code-o', '6', '0');
INSERT INTO `sys_menu` VALUES ('494', '493', '查看', null, 'cmssite:list,cmssite:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('495', '493', '新增', null, 'cmssite:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('496', '493', '修改', null, 'cmssite:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('497', '493', '删除', null, 'cmssite:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('498', '0', '支付管理', null, null, '0', 'fa fa-cog', '6', '0');
INSERT INTO `sys_menu` VALUES ('499', '498', '支付管理', 'pay/payway.html', null, '1', 'fa fa-file-code-o', '6', '0');
INSERT INTO `sys_menu` VALUES ('500', '499', '查看', null, 'payway:list,payway:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('501', '499', '新增', null, 'payway:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('502', '499', '修改', null, 'payway:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('503', '499', '删除', null, 'payway:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('504', '0', '小程序管理', null, null, '0', 'fa fa-weixin', '6', '0');
INSERT INTO `sys_menu` VALUES ('505', '313', '入库单管理', 'wms/wmsenterstock.html', null, '1', 'fa fa-file-code-o', '6', '0');
INSERT INTO `sys_menu` VALUES ('506', '505', '查看', null, 'wmsenterstock:list,wmsenterstock:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('507', '505', '新增', null, 'wmsenterstock:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('508', '505', '修改', null, 'wmsenterstock:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('509', '505', '删除', null, 'wmsenterstock:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('510', '313', '入库单明细管理', 'wms/wmsenterstockdetail.html', null, '1', 'fa fa-file-code-o', '6', '0');
INSERT INTO `sys_menu` VALUES ('511', '510', '查看', null, 'wmsenterstockdetail:list,wmsenterstockdetail:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('512', '510', '新增', null, 'wmsenterstockdetail:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('513', '510', '修改', null, 'wmsenterstockdetail:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('514', '510', '删除', null, 'wmsenterstockdetail:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('515', '313', '出库单管理', 'wms/wmsleavestock.html', null, '1', 'fa fa-file-code-o', '6', '0');
INSERT INTO `sys_menu` VALUES ('516', '515', '查看', null, 'wmsleavestock:list,wmsleavestock:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('517', '515', '新增', null, 'wmsleavestock:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('518', '515', '修改', null, 'wmsleavestock:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('519', '515', '删除', null, 'wmsleavestock:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('520', '313', '出库单明细管理', 'wms/wmsleavestockdetail.html', null, '1', 'fa fa-file-code-o', '6', '0');
INSERT INTO `sys_menu` VALUES ('521', '520', '查看', null, 'wmsleavestockdetail:list,wmsleavestockdetail:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('522', '520', '新增', null, 'wmsleavestockdetail:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('523', '520', '修改', null, 'wmsleavestockdetail:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('524', '520', '删除', null, 'wmsleavestockdetail:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('525', '313', '库存管理', 'wms/wmsstockpile.html', null, '1', 'fa fa-file-code-o', '6', '0');
INSERT INTO `sys_menu` VALUES ('526', '525', '查看', null, 'wmsstockpile:list,wmsstockpile:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('527', '525', '新增', null, 'wmsstockpile:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('528', '525', '修改', null, 'wmsstockpile:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('529', '525', '删除', null, 'wmsstockpile:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('530', '313', '仓库管理', 'wms/wmsstorehouse.html', null, '1', 'fa fa-file-code-o', '6', '0');
INSERT INTO `sys_menu` VALUES ('531', '530', '查看', null, 'wmsstorehouse:list,wmsstorehouse:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('532', '530', '新增', null, 'wmsstorehouse:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('533', '530', '修改', null, 'wmsstorehouse:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('534', '530', '删除', null, 'wmsstorehouse:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('535', '313', '退货单管理', 'wms/wmsbacksale.html', null, '1', 'fa fa-file-code-o', '6', '0');
INSERT INTO `sys_menu` VALUES ('536', '535', '查看', null, 'wmsbacksale:list,wmsbacksale:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('537', '535', '新增', null, 'wmsbacksale:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('538', '535', '修改', null, 'wmsbacksale:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('539', '535', '删除', null, 'wmsbacksale:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('540', '313', '退货单明细管理', 'wms/wmsbacksaledetail.html', null, '1', 'fa fa-file-code-o', '6', '0');
INSERT INTO `sys_menu` VALUES ('541', '540', '查看', null, 'wmsbacksaledetail:list,wmsbacksaledetail:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('542', '540', '新增', null, 'wmsbacksaledetail:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('543', '540', '修改', null, 'wmsbacksaledetail:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('544', '540', '删除', null, 'wmsbacksaledetail:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('545', '313', '退库单管理', 'wms/wmsbackstock.html', null, '1', 'fa fa-file-code-o', '6', '0');
INSERT INTO `sys_menu` VALUES ('546', '545', '查看', null, 'wmsbackstock:list,wmsbackstock:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('547', '545', '新增', null, 'wmsbackstock:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('548', '545', '修改', null, 'wmsbackstock:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('549', '545', '删除', null, 'wmsbackstock:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('550', '313', '退库单明细管理', 'wms/wmsbackstockdetail.html', null, '1', 'fa fa-file-code-o', '6', '0');
INSERT INTO `sys_menu` VALUES ('551', '550', '查看', null, 'wmsbackstockdetail:list,wmsbackstockdetail:info', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('552', '550', '新增', null, 'wmsbackstockdetail:save', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('553', '550', '修改', null, 'wmsbackstockdetail:update', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('554', '550', '删除', null, 'wmsbackstockdetail:delete', '2', null, '6', '0');
INSERT INTO `sys_menu` VALUES ('555', '314', '会员统计', 'statistics/statistics01.html', '', '1', 'fa fa-line-chart', '6', '0');
INSERT INTO `sys_menu` VALUES ('556', '314', '订单统计', 'statistics/order.html', null, '1', 'fa fa-file-code-o', '6', '0');
INSERT INTO `sys_menu` VALUES ('557', '314', '库存统计', 'statistics/wms.html', null, '1', 'fa fa-file-code-o', '6', '0');
INSERT INTO `sys_menu` VALUES ('558', '504', '小程序管理', 'wxxcx/xcx.html', null, '1', 'fa fa-file-code-o', '6', '0');
